/*drop table if exists ADDRESS_AUD;
drop table if exists ADDRESS_REV;
drop table if exists ADDRESS;*/
drop table if exists ACCOUNT_AUD;
drop table if exists ACCOUNT_REV;
drop table if exists ACCOUNT;
drop table if exists CUSTOMER_AUD;
drop table if exists CUSTOMER_REV;
drop table if exists CUSTOMER;

/*drop sequence if exists ADDRESS_UNIQUE_ID_SEQ;
drop sequence if exists ADDRESS_ID_SEQ;*/
drop sequence if exists ACCOUNT_UNIQUE_ID_SEQ;
drop sequence if exists ACCOUNT_ID_SEQ;
drop sequence if exists CUSTOMER_UNIQUE_ID_SEQ;
drop sequence if exists CUSTOMER_ID_SEQ;


create table CUSTOMER
(
    ID               number(10)        not null,
    UNIQUE_ID        varchar2(10)      not null,
    NAME             varchar2(50 char) not null,
    EMAIL            varchar2(50 char) not null,
    TELEPHONE        varchar2(15 char) not null,
    CREATED_BY       varchar2(50 char) not null,
    LAST_MODIFIED_BY varchar2(50 char) not null,
    INSERT_TIMESTAMP timestamp(6) default CURRENT_TIMESTAMP,
    UPDATE_TIMESTAMP timestamp(6) default CURRENT_TIMESTAMP
);

alter table CUSTOMER
    add constraint CUSTOMER_pk
        primary key (ID);

alter table CUSTOMER
    add constraint CUSTOMER_uk
        unique (UNIQUE_ID);

create table CUSTOMER_REV
(
    REV      integer generated by default as identity,
    REVTSTMP bigint,
    USERNAME varchar(255) not null,
    primary key (REV)
);

create table CUSTOMER_AUD
(
    ID               number(10)        not null,
    REV              integer           not null,
    REVTYPE          tinyint,
    UNIQUE_ID        varchar2(10)      not null,
    NAME             varchar2(50 char) not null,
    EMAIL            varchar2(50 char) not null,
    TELEPHONE        varchar2(15 char) not null,
    CREATED_BY       varchar2(50 char) not null,
    LAST_MODIFIED_BY varchar2(50 char) not null,
    INSERT_TIMESTAMP timestamp(6) default CURRENT_TIMESTAMP,
    UPDATE_TIMESTAMP timestamp(6) default CURRENT_TIMESTAMP,
    primary key (ID, REV)
);

alter table CUSTOMER_AUD
    add constraint CUSTOMER_AUD_REV_fk
        foreign key (REV)
            references CUSTOMER_REV;

create table ACCOUNT
(
    ID               number(10)        not null,
    CUSTOMER_ID      number(10)        not null,
    UNIQUE_ID        varchar2(10)      not null,
    NAME             varchar2(50 char) not null,
    IBAN             varchar2(35 char) not null,
    BIC              varchar2(11 char) not null,
    AMOUNT           decimal(10, 2)    not null,
    CREATED_BY       varchar2(50 char) not null,
    LAST_MODIFIED_BY varchar2(50 char) not null,
    INSERT_TIMESTAMP timestamp(6) default CURRENT_TIMESTAMP,
    UPDATE_TIMESTAMP timestamp(6) default CURRENT_TIMESTAMP
);

alter table ACCOUNT
    add constraint ACCOUNT_pk
        primary key (ID);

alter table ACCOUNT
    add constraint ACCOUNT_fk
        foreign key (CUSTOMER_ID) references CUSTOMER (ID)
            on delete cascade;

alter table ACCOUNT
    add constraint ACCOUNT_uk
        unique (CUSTOMER_ID, UNIQUE_ID);

create table ACCOUNT_REV
(
    REV      integer generated by default as identity,
    REVTSTMP bigint,
    USERNAME varchar(255) not null,
    primary key (REV)
);

create table ACCOUNT_AUD
(
    ID               number(10)        not null,
    REV              integer           not null,
    REVTYPE          tinyint,
    CUSTOMER_ID      number(10)        not null,
    UNIQUE_ID        varchar2(10)      not null,
    NAME             varchar2(50 char) not null,
    IBAN             varchar2(35 char) not null,
    BIC              varchar2(11 char) not null,
    AMOUNT           decimal(10, 2)    not null,
    CREATED_BY       varchar2(50 char) not null,
    LAST_MODIFIED_BY varchar2(50 char) not null,
    INSERT_TIMESTAMP timestamp(6) default CURRENT_TIMESTAMP,
    UPDATE_TIMESTAMP timestamp(6) default CURRENT_TIMESTAMP,
    primary key (ID, REV)
);

alter table ACCOUNT_AUD
    add constraint ACCOUNT_AUD_REV_fk
        foreign key (REV)
            references ACCOUNT_REV;

/*create table ADDRESS
(
    ID               number(10)        not null,
    CUSTOMER_ID      number(10)        not null,
    UNIQUE_ID        varchar2(10)      not null,
    ADDRESS_LINE_1   varchar2(50 char) not null,
    ADDRESS_LINE_2   varchar2(50 char) not null,
    CITY             varchar2(35 char) not null,
    STATE            varchar2(20 char) not null,
    ZIP_CODE         varchar2(6 char)  not null,
    COUNTRY_CODE     varchar2(3 char)  not null,
    COUNTRY          varchar2(15 char) not null,
    CREATED_BY       varchar2(50 char) not null,
    LAST_MODIFIED_BY varchar2(50 char) not null,
    INSERT_TIMESTAMP timestamp(6) default CURRENT_TIMESTAMP,
    UPDATE_TIMESTAMP timestamp(6) default CURRENT_TIMESTAMP
);

alter table ADDRESS
    add constraint ADDRESS_pk
        primary key (ID);

alter table ADDRESS
    add constraint ADDRESS_fk
        foreign key (CUSTOMER_ID) references CUSTOMER (ID)
            on delete cascade;

alter table ADDRESS
    add constraint ADDRESS_uk
        unique (CUSTOMER_ID, UNIQUE_ID);

create table ADDRESS_REV
(
    REV      integer generated by default as identity,
    REVTSTMP bigint,
    USERNAME varchar(255) not null,
    primary key (REV)
);

create table ADDRESS_AUD
(
    ID               number(10)        not null,
    REV              integer           not null,
    REVTYPE          tinyint,
    CUSTOMER_ID      number(10)        not null,
    UNIQUE_ID        varchar2(10)      not null,
    ADDRESS_LINE_1   varchar2(50 char) not null,
    ADDRESS_LINE_2   varchar2(50 char) not null,
    CITY             varchar2(35 char) not null,
    STATE            varchar2(20 char) not null,
    ZIP_CODE         varchar2(6 char)  not null,
    COUNTRY_CODE     varchar2(3 char)  not null,
    COUNTRY          varchar2(15 char) not null,
    INSERT_TIMESTAMP timestamp(6) default CURRENT_TIMESTAMP,
    UPDATE_TIMESTAMP timestamp(6) default CURRENT_TIMESTAMP,
    primary key (ID, REV)
);

alter table ADDRESS_AUD
    add constraint ADDRESS_AUD_REV_fk
        foreign key (REV)
            references ADDRESS_REV;*/


create sequence CUSTOMER_ID_SEQ nocache;
create sequence CUSTOMER_UNIQUE_ID_SEQ nocache;
create sequence ACCOUNT_ID_SEQ nocache;
create sequence ACCOUNT_UNIQUE_ID_SEQ nocache;
/*create sequence ADDRESS_ID_SEQ nocache;
create sequence ADDRESS_UNIQUE_ID_SEQ nocache;*/
